### ISSUE TITLE
Web App Error (TypeError: Cannot read property 'cleanup' of undefined)

### ISSUE THREAD

**Issue by jchen232** [jameshadfield/phandango#111]
Hi, 

I've been playing around with the web app, and I've been able to visualize some output from Gubbins. However when I load phylogeny from RAxML or parsnp I get the following error. 

TypeError: Cannot read property 'cleanup' of undefined

I am using the chrome browser, and all trees have been formatted to be in Newick format and have the extension .tre.

**Comment by iosefward** [comment]
I'm also facing this same error but for Ariba output. I have a window open with v0.8.5 which works fine, but a new tab with 0.8.6 doesn't.

**Comment by jameshadfield** [comment]
@iosefward @jchen232 thanks for finding this. Have now reverted to `0.8.5`.
