### ISSUE TITLE
Save as vector image

### ISSUE THREAD

**Issue by simonrharris** [jameshadfield/phandango#12]
Allow saving output to pdf. Possibly via jsPDF?

**Comment by simonrharris** [comment]
For now output to svg. Although Macs don't have a default viewer of svgs, can be opened in Chrome and edited/changed format in Illustrator/Inkscape.

**Comment by simonrharris** [comment]
Help needed getting this to work on phylocanvas. All that needs to be done is for the canvas context to be replaced with the svg one, but I need help with that.

**Comment by jameshadfield** [comment]
effectively done (with a few bugs to fix) as of ca500aa
