### ISSUE TITLE
Citation link is broken

### ISSUE THREAD

**Issue by happykhan** [jameshadfield/phandango#125]
DOI link has an extra  ' at the end.

**Comment by simonrharris** [comment]
Hi Nabil,

Do you mean the link on the landing page? It's working for me.

Simon

**Comment by happykhan** [comment]
![doi](https://user-images.githubusercontent.com/1452696/41919767-30e97d62-7957-11e8-8332-f166cb56e347.png)

hi.

this is what I get when i click on the link from the README shown on https://github.com/jameshadfield/phandango

**Comment by simonrharris** [comment]
Thanks Nabil. I think it's fixed now.
