### ISSUE TITLE
Error encountered on Phandango site

### ISSUE THREAD

**Issue by herricjb** [jameshadfield/phandango#134]
Hello. I was looking at your [examples page on the Phandango website](http://jameshadfield.github.io/phandango/#/examples).  However, when I clicked on any of the examples, I got (variations of) the following error message:

Input error. File: https://cdn.rawgit.com/jameshadfield/phandangoExampleData/master/PMEN1_recombination/Spn23f.gff
AJAX failed for url https://cdn.rawgit.com/jameshadfield/phandangoExampleData/master/PMEN1_recombination/Spn23f.gff (status 0)

This froze up the page completely.

BTW, Phandango seems to be a great tool. I look forward to using it more.

**Comment by jameshadfield** [comment]
Hey @herricjb -- I just tried the examples and they worked for me 😕 (MacOS, chrome v69).
Perhaps rawgit was down temporarily? -- Is it still broken for you today?

**Comment by jameshadfield** [comment]
👍
