### ISSUE TITLE
Gubbins output colors

### ISSUE THREAD

**Issue by maguileraf** [jameshadfield/phandango#136]
Hello,

What do the red and blue represent when plotting the output from Gubbins?

Thank you.

**Comment by jameshadfield** [comment]
Blue represents recombination blocks identified at a leaf (terminal node) whereas red indicates blocks identified at internal nodes and thus inherited by multiple samples. See https://github.com/jameshadfield/phandango/wiki/How%20To%20Use#genomic-data for more. Colours chosen for consistency with https://science.sciencemag.org/content/331/6016/430
