### ISSUE TITLE
extracting numeric data from the graph at the base of the page

### ISSUE THREAD

**Issue by pjbiggs** [jameshadfield/phandango#145]
Hi James,
I am viewing Gubbins recombination in Phandango.  I was wondering if it was possible to get the numeric values from the graph at the base of the page, which in this case would be the recombination profiles?  I would imagine this would be a value for each genome position.
thanks,
Patrick

**Comment by jameshadfield** [comment]
Hey Patrick - you mean for a given position the number of recombination events observed there? Phandango won't export this in any useable way, so I imagine you'll have to write a small script to overlay regions in the gff files.

**Comment by pjbiggs** [comment]
Thanks James - a quick question, response and then now closure(!).  I will discuss this with my colleagues for a way forward.  Thanks again.
