### ISSUE TITLE
Metadata is not being displayed

### ISSUE THREAD

**Issue by mirulee** [jameshadfield/phandango#147]
I used Roary to generate the core_gene_alignment.aln.treefile.newick and gene_presence_absence.csv files. I added metadata.csv to visualize the data, but some entries are missing in the metadata display. I have verified and corrected both the sample names and the metadata entries, but the issue persists. Can you please help me resolve this problem?

![Phandango (2)](https://github.com/jameshadfield/phandango/assets/143674850/252cea49-a121-469f-9a01-ebd0e8594c58)

**Comment by jameshadfield** [comment]
> but some entries are missing in the metadata display. I have verified and corrected both the sample names and the metadata entries, but the issue persists.

Are you able to produce a small tree (you can create it manually, the tree shape's not important) with some samples for which the metadata is not appearing (and for some samples for which it is ok), together with a metadata file for just those samples? If you can share that data here I can try to work out what's going on

**Comment by mirulee** [comment]
Thank you. As you suggested, I've trimmed down the tree, but the issue seems to persist similarly. I'll attach both the metadata and tree files. I'd appreciate it if you could take a look.
![Phandango (3)](https://github.com/jameshadfield/phandango/assets/143674850/bda23a53-9af2-48cd-b9e7-914fbb1ae504)
[231010_metadata_test.csv](https://github.com/jameshadfield/phandango/files/12869778/231010_metadata_test.csv)
[core_gene_alignment.aln.treefile_test.newick.txt](https://github.com/jameshadfield/phandango/files/12869795/core_gene_alignment.aln.treefile_test.newick.txt)

**Comment by jameshadfield** [comment]
Thanks! The missing data is due to the taxa names having a trailing space in the metadata file, e.g. `"INU030"` in the tree has a trailing space in the metadata file `"INU030 "`. Removing the trailing spaces of the example data gives the following:

![image](https://github.com/jameshadfield/phandango/assets/8350992/3b3a8630-38da-48e6-898f-30de3556caa5)

**Comment by jameshadfield** [comment]
(Closing this as the underlying data files had strain names which didn't match. Please re-open if this doesn't fix the issue for you!)

**Comment by mirulee** [comment]
> Thanks! The missing data is due to the taxa names having a trailing space in the metadata file, e.g. `"INU030"` in the tree has a trailing space in the metadata file `"INU030 "`. Removing the trailing spaces of the example data gives the following:
> 
> ![image](https://user-images.githubusercontent.com/8350992/275354699-3b3a8630-38da-48e6-898f-30de3556caa5.png)


I hadn’t even thought about the spacebar. Thank you so much. Also, I would appreciate it if you could take down the post related to the sample names. Since it's our data, it could potentially be a sensitive matter.
