### ISSUE TITLE
GWAS manhattan plot not displaying colours when kmer/unitig positions (e.g. 140..160) used

### ISSUE THREAD

**Issue by rgladstone** [jameshadfield/phandango#151]
When I provide a plink file with unitig positions in the 3rd column, the colours in the 5th column are not displayed (all points are grey and sized corresponding to the length). If I use the same file but with just the start position the colours work so the general formatting of my file seems to be correct.

**Comment by rgladstone** [comment]
files here https://drive.google.com/drive/folders/1itDvjenQhG6kTRoPWwPwZor7dU0XgY2j?usp=sharing

**Comment by jameshadfield** [comment]
Hey Becca!

We did allow `x..y` coordinate formatting for seer output (from memory), so this should be working. I'll try to figure out why the colours are not displayed correctly in this case sometime in the next ~week.

For `x..y` coordinates it looks like the circle radius is variable. I don't remember why this is, but presumably this represents the kmer/unitig length? Is this what you expect / how you interpret it?

**Comment by rgladstone** [comment]
Hi James!

Yeah, when I played around with a mock plink file the radius of the circle changed with the x..y coordinates to represent the length. With longer unitigs the bigger circles will start to mask unitigs with higher or lower p-values (I accidentally made the x..y coordinates 100,000bp long and it covered the whole plot haha). I was actually kind of expecting ellipses stretched horizontally before it plotted) but it functions alright for short kmers/unitigs. In this subset the max unitig is only 83bp but the entire dataset has unitigs up to 4540bp long.

Thanks for your help 😊

From: james hadfield ***@***.***>
Reply to: jameshadfield/phandango ***@***.***>
Date: Wednesday, 21 February 2024 at 21:41
To: jameshadfield/phandango ***@***.***>
Cc: Rebecca Gladstone ***@***.***>, Author ***@***.***>
Subject: Re: [jameshadfield/phandango] GWAS manhattan plot not displaying colours when kmer/unitig positions (e.g. 140..160) used (Issue #151) [EXT]


Hey Becca!

We did allow x..y coordinate formatting for seer output (from memory), so this should be working. I'll try to figure out why the colours are not displayed correctly in this case sometime in the next ~week.

For x..y coordinates it looks like the circle radius is variable. I don't remember why this is, but presumably this represents the kmer/unitig length? Is this what you expect / how you interpret it?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jameshadfield_phandango_issues_151-23issuecomment-2D1957874833&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v6s6pvOcw9r40RHMkRZgykz0Wy3sTie-S9KIaOVCOlY&m=WhWu4kZCTbytUh3i4zW5yF9Nl07nZCHJ7wjuPLSKiiDNbwBWJowUy7c-0EbtLVxt&s=zcR1Ic59wSx16oItHCzPJAo3rJMlA0vzK5zHa_BjTH4&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGYKG5GWVL22V2JQJW2ASPDYUZLYXAVCNFSM6AAAAABDSYIGRKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJXHA3TIOBTGM&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v6s6pvOcw9r40RHMkRZgykz0Wy3sTie-S9KIaOVCOlY&m=WhWu4kZCTbytUh3i4zW5yF9Nl07nZCHJ7wjuPLSKiiDNbwBWJowUy7c-0EbtLVxt&s=pwV7mCzj6Q1fjNiophHaaQcmdTksgGr6kcTXXuZ3r9w&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

**Comment by jameshadfield** [comment]
> I was actually kind of expecting ellipses stretched horizontally before it plotted

This'd be better -- in the code it's actually called an `Ellipse` but it's just a circle. Let me know if you need this, it should be possible to improve this.

> When I provide a plink file with unitig positions in the 3rd column, the colours in the 5th column are not displayed (all points are grey and sized corresponding to the length).

This is now working as of version 1.3.1 - you may need to shift-refresh the page if you're still getting the old version (1.3.0)

**Comment by rgladstone** [comment]
I think it would be great to have ellipses, I have a couple more sets of analysis to look at this week and I’m sure there would be less overlapping with ellipses.

Thanks for looking into these!

From: james hadfield ***@***.***>
Reply to: jameshadfield/phandango ***@***.***>
Date: Monday, 26 February 2024 at 02:11
To: jameshadfield/phandango ***@***.***>
Cc: Rebecca Gladstone ***@***.***>, Author ***@***.***>
Subject: Re: [jameshadfield/phandango] GWAS manhattan plot not displaying colours when kmer/unitig positions (e.g. 140..160) used (Issue #151) [EXT]


I was actually kind of expecting ellipses stretched horizontally before it plotted

This'd be better -- in the code it's actually called an Ellipse but it's just a circle. Let me know if you need this, it should be possible to improve this.

When I provide a plink file with unitig positions in the 3rd column, the colours in the 5th column are not displayed (all points are grey and sized corresponding to the length).

This is now working as of version 1.3.1 - you may need to shift-refresh the page if you're still getting the old version (1.3.0)

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jameshadfield_phandango_issues_151-23issuecomment-2D1963151202&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v6s6pvOcw9r40RHMkRZgykz0Wy3sTie-S9KIaOVCOlY&m=iNewVEbzYKSa0cPN70eyGhikLRxcsKpG3g8CmV1IxiGTV34AnvN3VKnhWMMPMoIM&s=v_lSJazowRsazd3Z5-Pg2U8WysaU2nIuhUjNuO61rI8&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGYKG5AYHI6RIJSL2T7CAQLYVPONBAVCNFSM6AAAAABDSYIGRKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRTGE2TCMRQGI&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v6s6pvOcw9r40RHMkRZgykz0Wy3sTie-S9KIaOVCOlY&m=iNewVEbzYKSa0cPN70eyGhikLRxcsKpG3g8CmV1IxiGTV34AnvN3VKnhWMMPMoIM&s=aBEMYTgfp2qluMoR_W73hOTUBvArNaf0-Uk13KN5wg4&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA
