### ISSUE TITLE
issue regarding phandago upload file 

### ISSUE THREAD

**Issue by Aiman-UOP** [jameshadfield/phandango#160]
I am using phandago for visualizing Roary output files but dont know why its giving me error 
[Galaxy651-[Roary_on_data_374,_data_362,_and_others_Gene_Presence_Absence].csv](https://github.com/user-attachments/files/17615612/Galaxy651-.Roary_on_data_374._data_362._and_others_Gene_Presence_Absence.csv)
((Prokka_on_data_4__gff:0.002736510,(Prokka_on_data_7__gff:0.000000005,(Prokka_on_data_13__gff:0.064411239,Prokka_on_data_14__gff:0.000000005)1.000:0.018567471)0.992:0.000636349)0.974:0.000588663,((Prokka_on_data_10__gff:0.0,Prokka_on_data_11__gff:0.0,Prokka_on_data_12__gff:0.0):0.001043728,Prokka_on_data_3__gff:0.000685764)0.555:0.000181433,(Prokka_on_data_5__gff:0.000584133,((Prokka_on_data_17__gff:0.000454909,Prokka_on_data_2__gff:0.000454664)0.867:0.000268834,(Prokka_on_data_9__gff:0.000429809,(Prokka_on_data_1__gff:0.000771325,(Prokka_on_data_16__gff:0.000348466,(Prokka_on_data_6__gff:0.0,Prokka_on_data_8__gff:0.0):0.000105804)0.145:0.000122700)0.899:0.000435854)0.449:0.000278602)0.967:0.000511551)0.873:0.000192542);

**Comment by jameshadfield** [comment]
When I drag that CSV file and the associated newick string (as a file `Galaxy.nwk`) onto phandango.net everything works for me. If it's still not working for you could you let me know the exact browser you're using and any messages logged to the browser's console and I can take another look.
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/b492692d-f196-4aff-b552-f7b8838862c6">
