### ISSUE TITLE
Data Alignment Issue

### ISSUE THREAD

**Issue by smantovaneli** [jameshadfield/phandango#161]
Hi, I'm having trouble aligning the tree results with the metadata.csv file. I've tried various methods, but I'm still struggling

![image](https://github.com/user-attachments/assets/196bcaa2-9e77-4c04-b2a2-c700f5525563)

**Comment by jameshadfield** [comment]
Yeah that doesn't look ideal. Do the [example data sets](https://jameshadfield.github.io/phandango/#/examples) look ok for you? If they do it indicates something amiss with your data and if possible sharing those files here may help

**Comment by smantovaneli** [comment]
Hi James, thanks for getting back to me. I'm new to this and struggling a bit. Despite my table resembling the examples, the alignment isn't working. Additionally, the colors aren't effectively differentiating the values. Your help would be greatly appreciated! 🙂

[E.coli.zip](https://github.com/user-attachments/files/17876232/E.coli.zip)

**Comment by jameshadfield** [comment]
When I drag on the newick + csv within that zipfile everything looks ok for me:

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/2d1e8f78-319c-4c02-a480-a5c6a9889318">

I'd try using another browser to see if that changes anything

**Comment by smantovaneli** [comment]
Hi James, thanks for getting back!
I tried using another browser (Chrome) and the alignment worked. Currently, I use Opera.
Regarding the MLSTs (first column), is it possible to change the colors for better distinction? Some similar colors represent different MLSTs, making them appear identical.
![image](https://github.com/user-attachments/assets/fb2f0f1b-324c-4654-8167-6b06ba2b2e94)

The red arrow indicates the point where different values have similar colors, making them difficult to distinguish. Thank you for your assistance

**Comment by jameshadfield** [comment]
Yay - good to see it was as simple as a browser issue.

re: MLSTs, this is because they're all numbers so phandango's interpreting them as a continuous scale. If you change the column name to "ST:o" we'll use a better scale ([docs here](https://github.com/jameshadfield/phandango/wiki/Input%20data%20formats#metadata))

<img width="422" alt="image" src="https://github.com/user-attachments/assets/cd4ae361-e1b9-49f8-a26a-416af2a85e8b">

**Comment by smantovaneli** [comment]
Ahh perfect, thank you so much! I really appreciate the help.

One last question: I had set up this table with 1 to indicate the presence of a gene and left blank spaces to indicate absence. However, I wanted the absence of a gene to have some kind of coloration in the image, so I tried using 0 (as seen in the image on the right). However, in some cases, errors appear where some bacteria don’t have the gene, but the image shows a coloration indicating they do.

Do you know if it’s possible to assign a color to represent the absence?

![image](https://github.com/user-attachments/assets/7f0bd1a2-80e2-482c-b06c-488a1420dfb3)

**Comment by jameshadfield** [comment]
> errors appear where some bacteria don’t have the gene, but the image shows a coloration indicating they do.

What's the error? Are values representing "bacteria don’t have the gene" (empty string values) shown as the same colour "absence of a gene" (encoded as "0")? If you hover over those colours does the pop-up distinguish between the underlying values?

**Comment by smantovaneli** [comment]
For example, in this image, I hovered over the purple coloration, and one shows 0 while the other shows 1.
The 0 was supposed to be orange, representing the absence of the gene, not purple.

![image](https://github.com/user-attachments/assets/982165c0-770e-4e24-8453-22d9d22cbe0f)

**Comment by jameshadfield** [comment]
> The 0 was supposed to be orange, representing the absence of the gene, not purple.

Ahh, ok, I understand. From the [metadata docs](https://github.com/jameshadfield/phandango/wiki/Input%20data%20formats#metadata): 

> If you want multiple columns to use the same colours for the same values (e.g. so that the value 42 is the same colour in each column), then group these columns by adding an integer to the suffix - e.g. :o1. You can have as many groups as you like.

**Comment by smantovaneli** [comment]
Thank you, James! Your assistance was invaluable. I had previously attempted to change colors following instructions, but it worked this time.
Lastly, does Phandango automatically generate a legend based on the chosen colors, or must I create it manually?
![image](https://github.com/user-attachments/assets/c2a47f00-9543-427b-bbb0-67efd344d63b)

**Comment by jameshadfield** [comment]
No problem - Pressing `k` shows a legend!
