### ISSUE TITLE
Metadata colours

### ISSUE THREAD

**Issue by katholt** [jameshadfield/phandango#62]
Awesome work on this guys, I absolutely love it!

Just wondering, is there a way to control the colours used for metadata? Or to print a legend for these colours?

**Comment by jameshadfield** [comment]
Hi Kat, this is something i'm working on in the dev version which should be up this Friday (it's the 'redux' branch, but it's still got a few bugs).

Specifically, custom colours can be used by specifying them in an adjacent column of the csv file. The new version is much better at guessing the "type" of the data in a column, but this is a surprisingly hard problem, so you'll also be able to write things like `serotype:c` to interpret this column as categorical and use an appropriate colour spectrum. We've also got a legend/key that sort of pops up when you press `k` but any suggestions on how to best display this are welcome. 

Great to hear it's being used, all suggestions are welcome!

**Comment by jameshadfield** [comment]
@katholt I haven't forgotten about this! Will be implemented soon.
But there is now a key for the metadata - toggle it by pressing `k`

**Comment by jameshadfield** [comment]
Finally!

All information https://github.com/jameshadfield/phandango/wiki/Input-data-formats#metadata and https://github.com/jameshadfield/phandango/wiki#metadata
