### ISSUE TITLE
Text cut off at edges of divs

### ISSUE THREAD

**Issue by simonrharris** [jameshadfield/phandango#66]

**Comment by jameshadfield** [comment]
What exactly do you mean, the annotation info boxes? Screenshots??

And what would be the preferred solution -- if there's a LOT of info in the GFF this has to be trimmed somewhere I think.

**Comment by simonrharris** [comment]
Sorry, I mean things like the y-axis scale of plots (top value) and the left and right-most values on the genome scale.

Solutions - move them in/down a bit (e.g. 1/2 font size) or something cleverer

**Comment by jameshadfield** [comment]
Ahh ok. I'll work on this. The solution is to make these div elements separate to the canvas. I do that already with the info boxes for metadata / genes etc
