### ISSUE TITLE
Link to "Live Version" is ERROR 404 - still links to JScandy

### ISSUE THREAD

**Issue by tseemann** [jameshadfield/phandango#67]
(on the github.com README.md)

**Comment by jameshadfield** [comment]
I believe i've fixed this. At least for me http://jameshadfield.github.io/JScandy now redirects to http://jameshadfield.github.io/phandango

I'll leave this open for a bit just in case it isn't working as expected

**Comment by tseemann** [comment]
Seems ok now, thank you.
