### ISSUE TITLE
phylocanvas SVG output broken on retina display

### ISSUE THREAD

**Issue by jameshadfield** [jameshadfield/phandango#83]

**Comment by simonrharris** [comment]
Not easy for me to test this without a retina  display, but I'll take a look

**Comment by jameshadfield** [comment]
fixed in 44cadff but it's not perfect and sometimes there is weird (i.e. hard to reproduce) behaviour

On retina screens, after printing to SVG, the tree redraws in a different position. Sometimes this happens on non-retina screens as well.
