### ISSUE TITLE
Make work in Firefox

### ISSUE THREAD

**Issue by simonrharris** [jameshadfield/phandango#91]

**Comment by simonrharris** [comment]
Have fixed zooming with the mouse wheel, drag resizing and save to svg but there's something making it insanely slow

**Comment by simonrharris** [comment]
There's also a bug with phylocanvas cmd zoom in Firefox. I've put in an issue with them about it.

**Comment by jameshadfield** [comment]
916456a d8b584a 9edc93a 2f0b3f0
