### ISSUE TITLE
Recalculate line graph when subtree is drawn

### ISSUE THREAD

**Issue by leosanbu** [jameshadfield/phandango#97]
I'm not sure if a previous version did this, but when you select a clade, it would be useful that the peaks at the bottom were recalculated for that clade.

**Comment by jameshadfield** [comment]
Still works for me!

What data-types / actions do you do that don't cause a second (gray) line to be displayed?

**Comment by leosanbu** [comment]
Ahh!! I can see it now! But you need to select the whole tree, when it is blue (selected), then the grey line appears. I was thinking more of a clade-scaled plot, just to display the info for the selected clade, but that way you loose the big hotspots, and it is useful to have both.

What about making a 3rd axis on the right to have both lines scaled at their own maximum? The thing is that small hotspots in one clade are so small in the overall scale that you cannot see them. Or maybe if in the future you add options when right-clicking, giving the option of showing one line or the other could also be helpful.

Just a suggestion for future improvements!

**Comment by jameshadfield** [comment]
OK, so when a subclade is displayed (by right clicking on the tree) the black line plot must be redisplayed?

**Comment by leosanbu** [comment]
In my opinion it could be rescaled just to the selected taxa, which is the grey line. But if the black line has very high peaks, then the grey line can be very flat. But it is a suggestion, maybe other people prefer to keep both this way!

**Comment by simonrharris** [comment]
I think James has the best resolution - when a subtree is drawn recalculate the plot. James, is it possible to make this more general. i.e. could it calculate the plot for displayed blocks only, so recalculate when selecting a subtree or a new tree is dropped?

**Comment by jameshadfield** [comment]
Yes, there are (already) listeners for *subtree* and *loaded* so just a matter of triggering line re-calculation then. Will have to re-write linegraph code so it only considers blocks with (all?) taxa in *activeTaxa* (i.e. displayed by tree)

**Comment by leosanbu** [comment]
Sounds good!!
